### ISSUE TITLE
'POINTER(IUnknown)'

### ISSUE THREAD

**Issue by GoToHell3ro** [ebrahimraeyat/etabs_api#2]
Hi dude, do you have suggestions for solve this error? I can't connect to etabs. 
SapModel=EtabsObject.SapModel
AttributeError: 'POINTER(IUnknown)' object has no attribute 'SapModel'

I have tested comtypes v1.1.6,7,8,10,11.

**Comment by ebrahimraeyat** [comment]
Hi, run ETABS with Administrator permission. most of the time it removes the errors.

**Comment by ebrahimraeyat** [comment]
If you have 2 or more ETABS installed, go to the ETABS installation folder and run RegisterETABS.EXE as an administrator permission.
