### ISSUE TITLE
Can you use chat gpt to rewite it in excel vba

### ISSUE THREAD

**Issue by AhmedAbdelfatahGH** [ebrahimraeyat/etabs_api#3]
Not each civil engineer has python installed on there pc

**Comment by ebrahimraeyat** [comment]
Hello @ahmed-m-abdelfatah. 
Thanks for your interest.
I use this library in my [civiltools ](https://github.com/ebrahimraeyat/civilTools)and [OSAFE ](https://github.com/ebrahimraeyat/OSAFE) workbenches in [FreeCAD](https://www.freecad.org/). FreeCAD did not support vb.
although a person must be a programmer to use this library, thus as python is open source and free, you can install it on windows and then:
`pip install etabs-api`

and use it.

**Comment by AhmedAbdelfatahGH** [comment]
Ok,  but could you add a YouTube video of how to use this on windows

**Comment by ebrahimraeyat** [comment]
Thanks. I add Readme examples. You can find more examples in test folder.
